In [38]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy as sp

In [39]:
csn = pd.read_excel("uitslag_csn.xlsx")

# 1
Bepaal de gemiddelde scores per student en toon de hoogstscorende eerst.

In [40]:
csn_results = pd.DataFrame([v.mean()*10 for v in csn.values[:, [csn.columns.get_loc(v) for v in csn.columns if v.startswith("Score")]]], columns=["Mean"])
csn_results.sort_values(by="Mean", ascending=False)

      Mean
64   10.00
338   9.75
435   9.50
76    9.50
80    9.50
104   9.50
418   9.25
474   9.25
18    9.25
465   9.25
169   9.00
36    9.00
189   9.00
292   9.00
87    9.00
398   9.00
47    9.00
19    9.00
238   9.00
7     9.00
337   9.00
312   8.75
345   8.75
131   8.75
193   8.75
342   8.75
203   8.75
176   8.75
463   8.75
262   8.75
..     ...
148   4.25
278   4.25
86    4.00
3     4.00
8     4.00
327   4.00
78    4.00
395   4.00
394   4.00
181   4.00
97    4.00
66    4.00
114   4.00
119   3.75
461   3.75
249   3.75
261   3.75
30    3.75
46    3.75
470   3.75
137   3.75
197   3.50
270   3.50
330   3.50
133   3.25
25    3.00
462   3.00
411   3.00
286   2.75
17    2.75

[479 rows x 1 columns]

# 2
Voeg twee kolommen per student toe
1. cijfer = $\frac{9}{30}(\sum_{i=1}^{40}{Score.i}-10) + 1$
2. eindcijfer = $\max(1, cijfer)$. (Tip: gebruik ***np.maximum***)

In [48]:
csn_results["Cijfer"] = [9/30*(v.mean()*10-10)+1 for v in csn.values[:, [csn.columns.get_loc(v) for v in csn.columns if v.startswith("Score")]]]
#csn_results["Eindcijfer"] = [max(1, 9/30*(v.mean()*10-10))+1 for v in csn.values[:, [csn.columns.get_loc(v) for v in csn.columns if v.startswith("Score")]]]
csn_results["Eindcijfer"] = np.maximum(1, csn_results["Cijfer"])
csn_results

     Mean  Eindcijfer  Cijfer
0    5.25         1.0  -0.425
1    5.50         1.0  -0.350
2    8.50         1.0   0.550
3    4.00         1.0  -0.800
4    4.75         1.0  -0.575
5    6.50         1.0  -0.050
6    6.00         1.0  -0.200
7    9.00         1.0   0.700
8    4.00         1.0  -0.800
9    7.00         1.0   0.100
10   6.25         1.0  -0.125
11   6.75         1.0   0.025
12   5.75         1.0  -0.275
13   5.50         1.0  -0.350
14   5.25         1.0  -0.425
15   8.25         1.0   0.475
16   6.75         1.0   0.025
17   2.75         1.0  -1.175
18   9.25         1.0   0.775
19   9.00         1.0   0.700
20   7.00         1.0   0.100
21   7.25         1.0   0.175
22   4.75         1.0  -0.575
23   7.00         1.0   0.100
24   6.50         1.0  -0.050
25   3.00         1.0  -1.100
26   5.75         1.0  -0.275
27   7.75         1.0   0.325
28   6.50         1.0  -0.050
29   6.75         1.0   0.025
..    ...         ...     ...
449  7.50         1.0   0.250
450  6.00         1.0  -0.200
451  5.50         1.0  -0.350
452  7.50         1.0   0.250
453  5.00         1.0  -0.500
454  5.00         1.0  -0.500
455  7.25         1.0   0.175
456  6.25         1.0  -0.125
457  5.25         1.0  -0.425
458  8.25         1.0   0.475
459  5.25         1.0  -0.425
460  8.00         1.0   0.400
461  3.75         1.0  -0.875
462  3.00         1.0  -1.100
463  8.75         1.0   0.625
464  4.75         1.0  -0.575
465  9.25         1.0   0.775
466  6.00         1.0  -0.200
467  7.25         1.0   0.175
468  6.00         1.0  -0.200
469  5.75         1.0  -0.275
470  3.75         1.0  -0.875
471  6.25         1.0  -0.125
472  5.25         1.0  -0.425
473  5.25         1.0  -0.425
474  9.25         1.0   0.775
475  7.25         1.0   0.175
476  5.75         1.0  -0.275
477  6.75         1.0   0.025
478  5.50         1.0  -0.350

[479 rows x 3 columns]

# 3
Bepaal het totale gemiddelde over alle studenten. Doe dit nogmaals, maar dan alleen de studenten die een voldoende hebben gescoord.

In [ ]:
csn_win = pd.DataFrame([True if v.mean()*10 >= 5.5 else False for v in csn.values[:, [csn.columns.get_loc(v) for v in csn.columns if v.startswith("Score")]]], columns=["Mean"])
csn_win

In [ ]:
mu = csn_results.Eindcijfer.mean()
sigma = csn_results.Eindcijfer.std()
normal_verdeling = sp.stats.norm(mu, sigma)

x = np.linspace(-5, 15, 1000)
y = normal_verdeling.pdf(x)

plt.plot(x, y)
plt.show()